name: galileo_security
version: 3.0.1
description: Galileo infrastructure for improving security, rate limiting, and more.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/security
environment: 
  sdk: ">=2.10.0 <3.0.0"

dependencies: 
  galileo_framework: ^3.0.2 
  crypto: ^3.0.1 #Null safety

dev_dependencies: 
  galileo_auth: ^3.0.1
  galileo_production: ^2.0.3
  galileo_redis: ^3.0.0  
  galileo_test: ^3.0.1   
  galileo_validate: ^3.0.1  
  pedantic: ^1.11.0 #Null safety
  galileo_pretty_logging: ^3.0.0 #Null safety
  test: ^1.17.3   #Null safety
