name: galileo_client
version: 3.0.1
description: Support for querying galileo servers in the browser, Flutter, and command-line.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/client
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_http_exception: ^2.0.1 #Null safety
  collection: ^1.15.0  #Null safety
  http: ^0.13.3  #Null safety
  galileo_json_god: ^3.0.0  
  #dart_json_mapper: ^1.7.0
  meta: ^1.3.0 # Null safety
  path: ^1.8.0 # Null safety

dev_dependencies:
  galileo_framework: ^3.0.2 
  galileo_model: ^2.0.0   
  async: ^2.6.1 #Null safety
  build_runner: ^2.0.2 #Null safety
  build_web_compilers: ^3.0.0 #Null safety
  galileo_mock_request: ^1.0.8  #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
