name: galileo_typed_service
version: 3.0.0
description: Galileo services that use reflection to (de)serialize Dart objects.
homepage: https://github.com/galileo-dart/typed_service
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2 
  galileo_json_god: ^3.0.1

dev_dependencies:
  galileo_file_service: ^3.0.0     
  file: ^6.1.0 #Null safety
  logging: ^1.0.1 #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3  #Null safety
