name: angel_typed_service
version: 1.0.1
description: Angel services that use reflection to (de)serialize Dart objects.
homepage: https://github.com/angel-dart/typed_service
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  angel_framework: #^2.0.0-alpha
    path: ../framework
  json_god: ^2.0.0-beta
dev_dependencies:
  angel_file_service: #^2.0.0
    path: ../file_service
  file: ^5.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  test: ^1.15.7