name: vs_jael_language_server
version: 0.0.0
description: Language Server Protocol implementation for the Jael templating engine.
author: Tobe Osakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/vscode
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  args: ^1.0.0
#  dart_language_server: ^0.1.16
  file: ^5.0.0
  io: ^0.3.2
  jael: #^2.0.0
    path: ../../jael/jael
  jael_preprocessor: #^2.0.0
    path: ../../jael/jael_preprocessor
  json_rpc_2: ^2.0.0
  logging: ^0.11.3
  path: ^1.0.0
  source_span: ^1.0.0
  string_scanner: ^1.0.0
  symbol_table: ^2.0.0
executables:
  jael_language_server: jael_language_server