name: angel_poll
version: 1.0.0
description: package:angel_client support for "realtime" interactions with Angel via long polling.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.7.0 <3.0.0"
homepage: https://github.com/angel-dart/poll
dependencies:
  angel_client: # ^1.0.0
    path: ../client
  async: ">=1.10.0 <3.0.0"
  collection: ^1.14.12
dev_dependencies:
  angel_test: # ^1.1.0
    path: ../test
  test: ^1.15.7