name: galileo_poll
version: 3.0.0
description: package:galileo_client support for "realtime" interactions with Galileo via long polling.
author: Isaque Neves <insinfo2008@gmail.com>
environment:
  sdk: ">=2.10.0 <3.0.0"
homepage: https://github.com/insinfo/galileo/tree/master/packages/poll

dependencies:
  galileo_client: ^3.0.1   
  async: ^2.6.1 #Null safety
  collection: ^1.15.0 #Null safety

dev_dependencies:
  galileo_test: ^3.0.1  
  test: ^1.17.3 #Null safety
