description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "angel"
publish_to: "none"
dependencies: 
  angel_configuration: "^1.1.0"
  angel_framework: "^1.1.0"
  angel_migration: "^1.0.0-alpha"
  angel_model: "^1.0.0"
  angel_orm: "^1.0.0-alpha"
  angel_serialize: "^1.0.0"
  angel_static: "^1.3.0"
dev_dependencies: 
  angel_hot: "^1.1.0"
  angel_migration_runner: "^1.0.0-alpha"
  angel_orm_generator: "^1.0.0-alpha"
  angel_serialize_generator: "^1.0.0"
  angel_test: "^1.1.0"
  build_runner: "^0.5.0"
  console: "^2.2.4"
  test: "^0.12.0"
environment: 
  sdk: ">=1.19.0"
