name: galileo_route
description: A powerful, isomorphic routing library for Dart. It is mainly used in the galileo framework, but can be used in Flutter and on the Web.
version: 5.0.1
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  #combinator: ^1.0.0
  galileo_combinator: ^1.1.1
  meta: ^1.3.0 # Null safety
  path: ^1.8.0 #Null safety
  string_scanner: ^1.1.0 #Null safety
  
dev_dependencies:
  build_runner: ^1.11.5
  build_web_compilers: ^2.16.4
  http: ^0.13.0
  pedantic: ^1.11.0
  test: ^1.16.5