name: galileo_graphql_generator
version: 3.0.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:galileo_graphql_server.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/graphql

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  #analyzer: ^0.39.0
  analyzer: ^1.5.0 #Null safety 
  galileo_model: ^2.0.0   
  galileo_serialize_generator: ^3.0.0 
  build: ^2.0.1 #Null safety
  build_config: ^1.0.0 #Null safety
  code_builder: ^4.0.0  #Null safety
  galileo_graphql_schema: ^3.0.0 
  recase: ^4.0.0 #Null safety
  source_gen: ^1.0.0 #Null safety

dev_dependencies:
  build_runner: ^2.0.2 #Null safety
  pedantic: ^1.11.0 #Null safety
