name: app
publish_to: none
dependencies:
  galileo_framework: ^2.0.0-alpha
  galileo_production: ^1.0.0-alpha
  galileo_proxy: ^2.0.0
  galileo_static: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
