name: galileo_mysql
version: 3.0.0
description: A library for connecting to and querying MySQL & MariaDB databases.
homepage: https://github.com/insinfo/galileo

authors:
- Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0 #Null safety
  crypto: ^3.0.1  #Null safety
  logging: ^1.0.1 #Null safety
  pool: ^1.5.0 #Null safety

dev_dependencies:
  mocktail: ^0.1.1
  options_file:
    git:
      url: https://github.com/rxlabz/optionsfile
      ref: ca741d4
  test: ^1.17.2 #Null safety
  pedantic: ^1.11.0  #Null safety
  build_runner: ^1.12.2 #2.0.1 Null safety

