name: angel_sync
version: 2.0.0
description: Easily synchronize and scale WebSockets using package:pub_sub.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/sync
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  angel_framework: #^2.0.0-alpha
    path: ../framework
  angel_websocket: #^2.0.0-alpha
    path: ../websocket
  pub_sub: ^2.0.0
  stream_channel: ^2.0.0
dev_dependencies:
  angel_test: #^2.0.0-alpha
    path: ../test
  test: ^1.15.7