name: galileo_sync
version: 3.0.0
description: Easily synchronize and scale WebSockets using package:galileo_pub_sub.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/sync

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2   
  galileo_websocket: ^3.0.2    
  galileo_pub_sub : ^3.0.1
  stream_channel: ^2.1.0 # Null safety

dev_dependencies:
  galileo_test: ^3.0.1   
  test: ^1.17.3 #Null safety
