name: galileo_data_loader
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
description: Batch and cache database lookups. Works well with GraphQL. Ported from JS.
homepage: https://github.com/insinfo/galileo/tree/master/packages/graphql

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  galileo_graphql_schema: ^3.0.0  
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
