name: galileo_serialize_generator
version: 3.0.0
description: Model serialization generators, designed for use with galileo. Combine with galileo_serialize for flexible modeling.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/blob/master/packages/serialize

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  galileo_model: ^2.0.0   
  galileo_serialize: ^3.0.0   
  analyzer: ^1.5.0  #Null safety
  build: ^2.0.1 #Null safety
  build_config: ^1.0.0 #Null safety
  essential_code_buffer: ^2.0.1 #Null safety
  code_builder: ^4.0.0 #Null safety
  meta: ^1.3.0 #Null safety
  path: ^1.8.0 #Null safety
  recase: ^4.0.0 #Null safety
  source_gen: ^1.0.0 #Null safety
  quiver: ^3.0.1 #Null safety

dev_dependencies:
  build_runner: ^2.0.2 #Null safety
  collection: ^1.15.0 #Null safety
  pedantic: ^1.11.0 # Null safety
  test: ^1.17.3 #Null safety

# dependency_overrides:
#   galileo_serialize:
#     path: ../galileo_serialize
