name: galileo_typed_buffer
description: Read and write typed data from binary buffer.
version: 3.0.0
homepage: https://github.com/insinfo/galileo
authors:
- Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.17.2
