name: galileo_hot
description: Supports hot reloading/hot code push of galileo servers on file changes.
version: 3.0.1
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework:  ^3.0.0
  galileo_websocket: ^3.0.0   
  charcode: ^1.2.0 #Null safety
  glob: ^2.0.1 #Null safety
  galileo_html_builder: 
  io: ^1.0.0 #Null safety
  path: ^1.8.0 #Null safety
  #https://pub.dev/packages/vm_service_lib
  #vm_service_lib: ^3.22.2+1
  #https://github.com/dart-lang/sdk/tree/master/pkg/vm_service
  vm_service: ^6.2.0 #Null safety
  watcher: ^1.0.0 #Null safety

dev_dependencies:
  http: ^0.13.3 # Null safety
  logging: ^1.0.1 #Null safety
  pedantic: ^1.11.0 #Null safety
