name: galileo_framework
version: 3.0.1
description: A high-powered HTTP server with dependency injection, routing and much more.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_container: ^2.2.1
  galileo_http_exception: ^2.0.1
  galileo_model: ^2.0.0  
  galileo_route: ^5.0.0
  charcode: ^1.0.0 #1.2.0  Null safety
  galileo_combinator: ^1.1.0
  file: ^6.1.0 #6.1.0 Null safety
  http_parser: '>3.1.4 <4.0.0'
  #http_server: ^0.9.0
  galileo_http_server: ^1.0.0 #1.0.0 Null safety
  http2: ^2.0.0 #2.0.0  Null safety
  logging: '>0.0.1 <2.0.0' # 1.0.1  Null safety
  matcher: ^0.12.0 # 0.12.10  Null safety
  galileo_merge_map: ^1.0.2

  meta: ^1.0.0 #1.3.0 Null safety
  mime: ^0.9.0 #^1.0.0 Null safety
  path: ^1.0.0 #1.8.0 Null safety
  
  galileo_mock_request: ^1.0.7 
  # pedantic: ^1.0.0
  #quiver_hashcode: ^2.0.0
  quiver: ^3.0.1 #Null safety
  recase: ^3.0.1 #recase 4.0.0 Null safety
  stack_trace: ^1.0.0 # 1.10.0  Null safety
  string_scanner: ^1.0.0 #1.1.0 Null safety
  tuple: ^2.0.0 #Null safety
  uuid: '>2.0.0 <3.5.4'  #uuid: ^3.0.4  Null safety

dev_dependencies:
  http: ^0.13.0 #0.13.1 Null safety
  io: ^1.0.0 #1.0.0 Null safety
  #pretty_logging: ^1.0.0
  test: ^1.15.7 # 1.17.2  Null safety

