name: galileo_framework
version: 4.0.0
description: A high-powered HTTP server with dependency injection, routing and much more.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_container: ^4.0.4 # Null safety #^2.2.1
  galileo_http_exception: ^2.0.2 #Null safety
  galileo_model: ^4.0.0 # Null safety
  galileo_route: ^6.0.1 
  galileo_combinator: ^4.0.3
  galileo_merge_map: #4.0.0  #Null safety #^1.0.2
  galileo_mock_request: ^4.0.0 #Null safety #^1.0.7  

  charcode: ^1.2.0 #  Null safety

  file: ^6.1.0 # Null safety
  http_parser: ^4.0.0  # Null safety
  galileo_http_server: ^1.0.1 # Null safety
  http2: ^2.0.0 #Null safety
  logging: '1.0.1' # Null safety
  matcher: ^0.12.10 #  Null safety
 
  meta: ^1.3.0 # Null safety
  mime: ^1.0.0 #Null safety
  path: ^1.8.0 # Null safety  
  
  quiver: ^3.0.1 #Null safety
  recase: ^4.0.0 # Null safety
  stack_trace: ^1.10.0 # Null safety
  string_scanner: ^1.1.0 # Null safety
  tuple: ^2.0.0 #Null safety
  uuid: ^3.0.4   # Null safety

dev_dependencies:
  http: ^0.13.1 # Null safety
  io: ^1.0.0 # Null safety
  #pretty_logging: ^1.0.0
  test: ^1.17.2 #  Null safety

