name: pretty_logging
version: 2.0.0
description: Standalone helper for colorful logging output, using pkg:io AnsiCode.
author: Tobe Osakwe <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/pretty_logging
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  io: ^1.0.0
  logging: ^1.0.0
dev_dependencies:
  pedantic: ^1.0.0
