name: angel_graphql
version: 1.1.0
description: The fastest + easiest way to get a GraphQL backend in Dart, using Angel.
homepage: https://github.com/angel-dart/graphql
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  angel_file_service: #^2.0.0
    path: ../../file_service
  angel_framework: #^2.0.0
    path: ../../framework
  angel_websocket: #^2.0.0
    path: ../../websocket
  angel_validate: #^2.0.0
    path: ../../validate
  graphql_parser: #^1.0.0
    path: ../graphql_parser
  graphql_schema: #^1.0.0
    path: ../graphql_schema
  graphql_server: #^1.0.0
    path: ../graphql_server
  http_parser: ^3.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  angel_serialize: #^2.0.0
    path: ../../serialize/angel_serialize
  file: ^5.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0

 