name: galileo_graphql
version: 1.1.0
description: The fastest + easiest way to get a GraphQL backend in Dart, using Galileo.
homepage: https://github.com/galileo-dart/graphql
author: Isaque Neves <insinfo2008@gmail.com>
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  galileo_file_service: #^2.0.0    
  galileo_framework: #^2.0.0    
  galileo_websocket: #^2.0.0   
  galileo_validate: #^2.0.0   
  graphql_parser: #^1.0.0   
  graphql_schema: #^1.0.0   
  graphql_server: #^1.0.0    
  http_parser: ^3.0.0
  web_socket_channel: ^1.0.0
dev_dependencies:
  galileo_serialize: #^2.0.0
    path: ../../serialize/galileo_serialize
  file: ^5.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0

 
