name: galileo_orm_test
version: 1.0.0
publish_to: none
description: Common tests for galileo ORM backends.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  galileo_migration:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_migration
  galileo_model:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/model
  galileo_orm:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm
  galileo_serialize:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/serialize/galileo_serialize
  test: ^1.15.7
dev_dependencies:
  galileo_orm_generator:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm_generator
  galileo_framework:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/framework
  build_runner: ^1.0.0
