name: yewtube
dependencies:
  galileo_configuration: ^2.0.0
  galileo_file_service: ^2.0.0
  galileo_framework: ^2.0.0-alpha
  galileo_jael: ^2.0.0
  galileo_serialize: ^2.0.0
  galileo_static: ^2.0.0
  galileo_validate: ^2.0.0
  uuid: ^2.0.0-rc.1
dev_dependencies:
  galileo_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
