builders:
  galileo_orm:
    import: "package:galileo_orm_generator/galileo_orm_generator.dart"
    builder_factories:
      - migrationBuilder
      - ormBuilder
    auto_apply: root_package
    build_to: cache
    build_extensions:
      .dart:
        - ".galileo_migration.g.part"
        - ".galileo_orm.g.part"
    required_inputs:
      - galileo_serialize.g.part
      - galileo_serialize_serializer.g.part
    applies_builders:
      - galileo_serialize_generator|galileo_serialize
      - source_gen|combining_builder
      - source_gen|part_cleanup"