name: eventsource_dart
description: A client and server implementation of Server-Sent Events.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/eventsource_dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  collection: ^1.15.0 #Null safety
  http: ^0.13.3 #Null safety
  http_parser: ^4.0.0  #Null safety
  logging: ^1.0.1 #Null safety
  sync: ^0.3.0 #Null safety

dev_dependencies:
  test: ^1.17.3 #Null safety
