name: angel_sql_postgres
description: PostgreSQL bindings for package:angel_sql, Angel's SQL solution.
version: 1.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/sql
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_sql:
    path: ../angel_sql
  postgres: ^1.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  http: ^0.12.0
  test: ^1.0.0