name: galileo_user_agent
version: 3.0.0
description: Galileo middleware to parse and inject a User Agent object into requests.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages//user_agent

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2   
  #user_agent: ^2.0.0
