name: galileo_combinator
version: 1.1.1
description: Packrat parser combinators that support static typing, generics, file spans, memoization, and more.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:  
  essential_code_buffer: ^2.0.1  #Null safety
  matcher: ^0.12.10  #  Null safety
  source_span: ^1.8.1   #Null safety
  string_scanner: ^1.1.0  #Null safety
  tuple: ^2.0.0 # Null safety

dev_dependencies:
  test: ^1.17.3 #Null safety