name: galileo_combinator
version: 1.1.0
description: Packrat parser combinators that support static typing, generics, file spans, memoization, and more.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  #code_buffer: ^1.0.0
  essential_code_buffer: ^2.0.1
  #matcher: ^0.12.0
  matcher: ^0.12.10
  #source_span: ^1.0.0
  source_span: ^1.8.1
  #string_scanner: ^1.0.0
  string_scanner: ^1.1.0
  #tuple: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  test: