name: galileo_orm
version: 3.0.0
description: Runtime support for galileo's ORM. Includes base classes for queries.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/galileo-dart/orm
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  intl: ^0.17.0
  meta: ^1.3.0
  string_scanner: ^1.1.0
dev_dependencies:
  galileo_model:    
  galileo_serialize:  
  galileo_serialize_generator:  
  build_runner: ^1.11.5
  pedantic: ^1.11.0
  test: ^1.16.5
