name: galileo_orm
version: 3.0.0
description: Runtime support for galileo's ORM. Includes base classes for queries.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/orm

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  charcode: ^1.2.0 #Null safety
  intl: ^0.17.0 #Null safety
  meta: ^1.3.0 #Null safety
  string_scanner: ^1.1.0 #Null safety

dev_dependencies:
  galileo_model: ^2.0.0 
  galileo_serialize: ^3.0.0 
  galileo_serialize_generator: ^3.0.0
  build_runner: ^2.0.2 #^1.11.5  #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
