name: angel_oauth2
author: Tobe O <thosakwe@gmail.com>
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://github.com/angel-dart/oauth2.git
version: 2.3.0
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies: 
  angel_framework: #^2.0.0-rc.0
    path: ../framework
  angel_http_exception: #^1.0.0
    path: ../http_exception
  crypto: ^2.0.0
dev_dependencies: 
  angel_validate: #^2.0.0-alpha
    path: ../validate
  angel_test: #^2.0.0-alpha
    path: ../test
  logging:
  oauth2: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.15.7
  uuid: ^2.0.0
