name: galileo_mustache4dart
version: 3.0.0
description: A mustache implementation for the Dart  language
homepage: https://github.com/insinfo/galileo/tree/master/packages/mustache4dart2
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.17.3 #Null safety
  #isolate: ^2.0.2
  galileo_isolate: ^3.0.0
