name: galileo_json_god
version: 3.0.0
authors:
  - Isaque Neves <insinfo2008@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  #dart2_constant: ^1.0.0
  logging: 

dev_dependencies:
  stack_trace: ^1.0.0
  test: any