name: galileo_serialize
version: 3.0.0
description: Static annotations powering galileo model serialization. Combine with galileo_serialize_generator for flexible modeling.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/blob/master/packages/serialize

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_model: ^2.0.0
  collection: ^1.15.0 #Null safety
  meta: ^1.3.0 #Null safety
  pedantic: ^1.11.0 #Null safety
  quiver: ^3.0.1 #Null safety
