name: galileo_graphql_server
version: 3.0.0
description: Base package for implementing GraphQL servers. You might prefer `package:galileo_galileo_graphql`, the fastest way to implement GraphQL backends in Dart.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/graphql

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_serialize: ^3.0.0    
  collection: ^1.15.0 #Null safety
  galileo_graphql_schema: ^3.0.0  
  galileo_graphql_parser: ^3.0.0 
  meta: ^1.3.0 #Null safety
  recase: ^4.0.0 #Null safety
  stream_channel: ^2.1.0 #Null safety
  tuple: ^2.0.0 #Null safety
  
dev_dependencies:
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety

#dependency_overrides:
#  graphql_parser:
#    path: ../graphql_parser
