name: "galileo_auth_twitter"
description: "package:galileo_auth strategy for Twitter login. Auto-signs requests."
homepage: "https://github.com/insinfo/galileo/tree/master/packages/auth_twitter"
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_auth:   
  galileo_framework:    
  http: ^0.13.0
  path: ^1.0.0
  twitter:    

dev_dependencies:
  logging: ^1.0.0
  pedantic: ^1.11.0
