name: galileo_migration_runner
version: 3.0.0
description: Command-line based database migration runner for galileo's ORM.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/orm/galileo_migration

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  galileo_migration: ^3.0.0    
  galileo_orm: ^3.0.0
  args: ^2.1.0 #Null safety
  charcode: ^1.2.0 #Null safety
  galileo_postgres: ^3.0.0 #Null safety
   
