name: galileo_migration_runner
version: 3.0.0
description: Command-line based database migration runner for galileo's ORM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/galileo-dart/migration
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  galileo_migration:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_migration
  galileo_orm:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm
  args: ^2.0.0
  charcode: ^1.2.0
  postgres:
    git: 
      url: https://github.com/insinfo/postgresql-dart
