name: galileo_cors
version: 3.0.0
description: Galileo CORS middleware. Port of expressjs/cors to the Galileo framework.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"
#publish_to: none

dependencies: 
  galileo_framework: ^3.0.0

dev_dependencies:
  #galileo_test:  
  http: ^0.13.0
  pedantic: ^1.11.0
  test: ^1.16.5
