name: galileo_markdown
version: 2.0.0
description: Galileo Markdown view generator. Write static sites, with no build step.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/markdown
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  galileo_framework: #^2.0.0-alpha
    path: ../framework
  file: ^5.0.0
  markdown: ^2.0.0
dev_dependencies:
  galileo_test: #^2.0.0
    path: ../test
  pedantic: ^1.0.0
  test: ^1.15.7
