name: galileo_auth
description: A complete authentication plugin for galileo. Includes support for stateless JWT tokens, Basic Auth, and more.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.0
  charcode: ^1.0.0
  collection: ^1.0.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  meta: ^1.0.0
  quiver: ^3.0.1

dev_dependencies:
  http: ^0.13.0
  io: ^1.0.0
  logging: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.15.7
