name: galileo_http_server
version: 1.0.0
description: Library of HTTP server classes.
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #mime: ^1.0.0
  #path: ^1.8.0
  meta: ^1.2.2 #1.3.0 Null safety
  path: ^1.7.0 #1.8.0 Null safety
  mime: any
  test_api: any


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
