name: galileo_http_server
version: 1.0.1
description: Library of HTTP server classes.
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:  
  meta: ^1.3.0  # Null safety
  path: ^1.8.0 # Null safety
  mime: ^1.0.0 #Null safety
  test_api: ^0.4.0 #Null safety


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
