name: galileo_auth_oauth2
description: galileo_auth strategy for OAuth2 login, i.e. Facebook, Github, etc.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/auth_oauth2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_auth: ^3.0.1 # Null safety 
  galileo_framework: ^3.0.2 # Null safety 
  http_parser: ^4.0.0 # Null safety 
  oauth2: ^2.0.0 #Null safety

dev_dependencies:
  logging: ^1.0.1 # Null safety
  pedantic: ^1.11.0 # Null safety