name: galileo_paginate
version: 3.0.0
description: Platform-agnostic pagination library, with custom support for the Galileo framework.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/paginate

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2 
  
dev_dependencies:
  galileo_test: ^3.0.1  
  logging: ^1.0.1 #Null safety
  test: ^1.17.3 #Null safety
