name: inflection3
version: 0.5.3+1
homepage: https://github.com/ericmartineau/dart-inflection
description: Grammatical Inflection encoders.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies: 
  test: any
authors: 
  - Tobe O <thosakwe@gmail.com>
  - George Moschovitis <george.moschovitis@gmail.com>
