name: galileo_eventsource
version: 3.0.0
description: Server-sent Events (SSE) plugin for galileo.
homepage: https://github.com/insinfo/galileo/tree/master/packages/eventsource
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2 
  galileo_websocket: ^3.0.1  
  eventsource_dart: ^3.0.0   
  stream_channel: ^2.1.0 #Null safety

dev_dependencies: 
  console: ^4.1.0 #Null safety
  logging: ^1.0.1 #Null safety
  test: ^1.17.3 #Null safety
