name: galileo_eventsource
version: 2.0.0
description: Server-sent Events (SSE) plugin for galileo.
homepage: https://github.com/galileo-dart/eventsource
author: Tobe O <thosakwe@gmail.com>
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  galileo_framework:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/framework
  galileo_websocket:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/websocket
  eventsource:
    git: 
      url: https://github.com/insinfo/dart-eventsource.git
  stream_channel: ^2.0.0
dev_dependencies: 
  console: ^4.0.0
  logging: ^1.0.0
  test: ^1.16.5
