name: galileo_wings

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.0    
  galileo_mock_request: ^1.0.8 

dev_dependencies:
  galileo_static: ^3.0.1 
  io: ^1.0.0 #Null safety
  pedantic: ^1.11.0 #Null safety
  galileo_pretty_logging: ^3.0.0 #Null safety
