name: galileo_container_generator
version: 2.0.1
author: Isaque Neves <insinfo2008@gmail.com>
description: Codegen support for using pkg:reflectable with pkg:galileo_container.
homepage: https://github.com/insinfo/galileo.git

#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_container: ^2.2.2
  reflectable: ^3.0.2 #Null safety

dev_dependencies:
  build_runner: ^2.0.2 #  Null safety
  build_test: ^2.1.0  # Null safety
  test: ^1.17.3 #  Null safety
