name: galileo_orm_service
version: 3.0.0
description: Service implementation that wraps over galileo ORM Query classes.
homepage: https://github.com/insinfo/galileo/tree/master/packages/orm/galileo_orm_service
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_framework: ^3.0.2   
  galileo_orm: ^3.0.0
   
dev_dependencies:
  galileo_migration: ^3.0.0
  galileo_migration_runner: ^3.0.0
  galileo_orm_generator: ^3.0.1
  galileo_orm_postgres: ^3.0.0
  galileo_orm_test: ^3.0.0
  galileo_serialize: ^3.0.0
  build_runner: ^2.0.2 #Null safety
  logging: ^1.0.1 #Null safety
  pedantic: ^1.11.0 #Null safety
  galileo_postgres: ^3.0.0 #Null safety
  test: ^1.17.3  #Null safety


#dependency_overrides:
#  galileo_migration:
#    path: ../galileo_migration
