name: galileo
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_serialize: ^3.0.0
  
dev_dependencies:
  galileo_serialize_generator: ^3.0.0 
  build_runner: ^2.0.2 #Null safety
