name: galileo_body_parser
author: Isaque Neves <insinfo2008@gmail.com>
version: 3.0.0
description: Parse request bodies and query strings in Dart. Supports JSON, URL-encoded, and multi-part bodies.
homepage: https://github.com/insinfo/galileo/tree/master/packages/body_parser

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  #dart2_constant: ^1.0.0
  http_parser: ^4.0.0 #Null safety
  galileo_http_server: ^1.0.1 #Null safety
  mime: ^1.0.0  #Null safety

dev_dependencies:
  http: ^0.13.3 #Null safety
  test: ^1.17.3 #Null safety
