name: galileo_orm_mysql
version: 3.0.1
description: MySQL support for galileo's ORM. Includes functionality for querying and transactions.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/orm

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_orm: ^3.0.0     
  logging: ^1.0.1 #Null safety
  pool: ^1.5.0 #Null safety
  galileo_sqljocky5: ^3.0.0 #Null safety

dev_dependencies:
  galileo_migration: ^3.0.0     
  galileo_orm_generator: ^3.0.1     
  galileo_orm_test: ^3.0.0     
  build_runner: ^2.0.2 #Null safety
  test: ^1.17.3  #Null safety

#dependency_overrides:
#  galileo_migration:
#    path: ../galileo_migration
#  galileo_orm_generator:
#    path: ../galileo_orm_generator
