name: galileo_websocket
description: Support for using pkg:galileo_client with WebSockets. Designed for galileo.
version: 3.0.2
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_auth: ^3.0.1
  galileo_client: ^3.0.1
  galileo_framework: ^3.0.2 
  galileo_http_exception: ^2.0.2 #Null safety
  http: ^0.13.3 #Null safety
  galileo_merge_map: ^1.0.2 
  meta: ^1.3.0 #Null safety
  stream_channel: ^2.1.0 #Null safety
  web_socket_channel: ^2.1.0 #Null safety

dev_dependencies:
  galileo_container: ^2.2.2  
  galileo_model: ^2.0.0   
  logging: ^1.0.1 #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
  
