name: galileo_mock_request
version: 1.0.7
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
    sdk: ">=2.10.0 <3.0.0"

dependencies:
  charcode: ">=1.0.0 <2.0.0"

dev_dependencies:
  angel_framework: ^2.1.0
  http: ^0.12.0
  test: ^1.14.0
