name: galileo_pub_sub
version: 3.0.1
description: Keep application instances in sync with a simple pub/sub API.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  json_rpc_2: ^3.0.0 #Null safety
  stream_channel: ^2.1.0  #Null safety
  uuid: ^3.0.4 #Null safety

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
  #test: ^1.0.0
