name: galileo_container 
#galileo #perola 
version: 2.2.2
author: Isaque Neves <insinfo2008@gmail.com>
description: A hierarchical DI container, and pluggable backends for reflection.
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  collection: ^1.15.0 #Null safety
  quiver: ^3.0.1 #Null safety 

dev_dependencies: 
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.2 #Null safety
