author: Isaque Neves <insinfo2008@gmail.com>
description: Database-agnostic relations between Galileo services.
homepage: "https://github.com/insinfo/galileo/tree/master/packages/relations"

name: galileo_relations
version: 3.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies: 
  galileo_framework: #^1.0.0-dev  

dev_dependencies:
  galileo_seeder: #^1.0.0   
  test: ^1.15.7
