name: galileo_file_security
version: 3.0.0
description: Middleware for securing file uploads.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/file_security

environment:
  sdk: ">=2.10.0 < 3.0.0"

dependencies:
  galileo_framework: ^3.0.0
  http: ^0.13.3 # Null safety
  logging: ^1.0.1 # Null safety
  http_parser: ^4.0.0  # Null safety
  path: ^1.8.0 # Null safety

dev_dependencies:
  galileo_validate: ^3.0.0
  galileo_test: ^3.0.1
  test: ^1.17.3 # Null safety
  uuid: ^3.0.4  #Null safety