name: galileo_configuration
description: Automatic YAML application configuration loader for galileo, with .env support.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.0
  dotenv: ^3.0.0-nullsafety.0
#  file: ^5.0.0
  galileo_merge_map: ^1.0.2
  yaml: ^3.1.0 #Null safety
  file:

dev_dependencies:  
  logging:
  io: ^1.0.0
#  logging: ^0.11.0
  pedantic: ^1.0.0
#  pretty_logging: ^1.0.0
  test: ^1.15.7
