name: galileo_task
version: 1.1.1
description: Support for running asynchronous jobs within Galileo. Ideal for large applications.
author: Isaque Neves <insinfo2008@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/galileo-dart/task
dependencies:
  galileo_framework: ^1.0.0
  uuid: ^0.5.3
dev_dependencies:
  mock_request: ^1.0.0
  test: ^0.12.0
