name: galileo_graphql_schema
version: 3.0.0
description: An implementation of GraphQL's type system in Dart. Basis of galileo_graphql_server.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/graphql

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  collection: ^1.15.0 # Null safety
  meta: ^1.3.0 # Null safety
  source_span: ^1.8.1  # Null safety

dev_dependencies:
  test: ^1.17.3 # Null safety
