name: galileo_proxy
description: Galileo middleware to forward requests to another server (i.e. pub serve).
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/proxy

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2    
  http: ^0.13.3 #Null safety
  http_parser: ^4.0.0  #Null safety
  path: ^1.8.0  #Null safety

dev_dependencies:
  galileo_test: ^3.0.1    
  logging: ^1.0.1 #Null safety
  galileo_mock_request: ^1.0.8
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3  #Null safety
  
