name: galileo_prompts
version: 2.0.0
description: Rich, simple, synchronous command-line prompt library for Dart.
homepage: https://github.com/insinfo/galileo/tree/master/packages/prompts
author: Isaque Neves <insinfo2008@gmail.com>

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  charcode: ^1.2.0 #Null safety
  io: ^1.0.0 #Null safety

dev_dependencies:
  pedantic: ^1.11.0  #Null safety
