name: galileo_flutter
version: 3.0.0
description: Widgets and helpers for developing Flutter clients for galileo applications.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/flutter

environment:
  sdk: ">=2.10.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter

  galileo_client: ^3.0.1
  galileo_websocket: ^3.0.1 
  async: ^2.6.1 #Null safety 
  meta: ^1.3.0 #Null safety
  shared_preferences: ^2.0.5 #Null safety
  uni_links: ^0.5.1  #Null safety
  url_launcher: ^6.0.3 #Null safety

dev_dependencies:
  #flutter_test:
    #sdk: flutter
  pedantic: any # ^1.11.0 Null safety