name: galileo_utf
version: 2.0.0

description: Provides common operations for manipulating Unicode sequences
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.2.0
