name: galileo_toggle
version: 3.0.0
description: Allows you to substitute one service for another while testing.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/toggle

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2 

dev_dependencies:
  #galileo_diagnostics: ^1.0.0
  galileo_test: ^3.0.1
  test: ^1.17.3 #Null safety
