name: angel_toggle
version: 1.0.0
description: Allows you to substitute one service for another while testing.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/toggle
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
dev_dependencies:
  angel_diagnostics: ^1.0.0
  angel_test: ^1.0.0
  test: ^0.12.15