name: galileo_merge_map
description: Combine multiple Maps into one. Equivalent to Object.assign in JS.
version: 1.0.2
homepage: https://github.com/insinfo/galileo.git
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  test:
