name: galileo_auth_instagram
version: 3.0.0
description: galileo_auth strategy for Instagram OAuth2 login.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/auth_instagram

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_auth: ^3.0.1
  instagram: ^1.0.0-beta
