name: angel_sql
version: 1.0.0
description: SQL-backed services for the Angel framework; generic backend.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/sql
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
dev_dependencies:
  angel_test: ^2.0.0-alpha
  http: ^0.12.0
  test: ^1.0.0