name: galileo_orm_generator
version: 3.0.0
description: Code generators for galileo's ORM. Generates query builder classes.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/galileo-dart/orm
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  analyzer: ">=0.35.0 <2.0.0"
  galileo_model:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/model
  galileo_serialize:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/serialize/galileo_serialize
  galileo_orm:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm
  galileo_serialize_generator:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/serialize/galileo_serialize_generator
  build: ^1.0.0
  build_config: ^0.4.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  inflection2: ^0.4.2
  meta: ^1.0.0
  path: ^1.0.0
  recase: ^3.0.1
  source_gen: ^0.9.0
dev_dependencies:
  galileo_framework:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/framework
  galileo_migration:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_migration
  #galileo_test: ^1.0.0
  build_runner: ^1.11.5
  collection: ^1.0.0
  pedantic: ^1.11.0
  postgres:
    git: 
      url: https://github.com/insinfo/postgresql-dart
  test: ^1.16.5
