name: galileo_migration
version: 3.0.0
description: Database migration runtime for galileo's ORM. Use this package to define schemas.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/migration

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  galileo_orm: ^3.0.0 
  
