name: star_wars
publish_to: none
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  #galileo_file_service: ^1.0.0
  galileo_graphql:
    path: ../galileo_graphql
  galileo_hot: #^2.0.0-alpha
    path: ../../hot
  galileo_serialize: #^2.0.0
    path: ../../serialize/galileo_serialize
  io: ^0.3.2
dev_dependencies:
  galileo_serialize_generator: #^2.0.0
    path: ../../serialize/galileo_serialize_generator
  build_runner: ^1.0.0
  graphql_generator:
    path: ../graphql_generator
dependency_overrides:
  graphql_parser:
    path: ../graphql_parser
  graphql_schema:
    path: ../graphql_schema
  graphql_server:
    path: ../graphql_server
    
