name: star_wars
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_file_service: ^3.0.0 
  galileo_graphql: ^3.0.0     
  galileo_hot: ^3.0.1   
  galileo_serialize: ^3.0.0   
  io: ^1.0.0 # Null safety
  galileo_graphql_parser: ^3.0.0 
  galileo_graphql_schema: ^3.0.0  
  galileo_graphql_server: ^3.0.0 
  galileo_container: ^2.2.2

dev_dependencies:
  galileo_serialize_generator: ^3.0.0 
  build_runner: ^2.0.2 # Null safety
  galileo_graphql_generator: ^3.0.0  

#dependency_overrides:
 # graphql_parser:   
 # graphql_schema:    
 # graphql_server:
   
    
