name: galileo_sqljocky5
version: 3.0.1
description: MySQL driver for Dart with support for prepared statements, transactions and connection pooling.
documentation:
homepage: https://github.com/insinfo/galileo

authors:
- Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0 #Null safety
  collection: ^1.15.0 #Null safety
  crypto: ^3.0.1 #Null safety
  synchronized: ^3.0.0 #Null safety
  galileo_typed_buffer: ^3.0.0 #Null safety

dev_dependencies:
  test: ^1.17.2 #Null safety
