name: galileo_mustache
description: Mustache view generator for Galileo.
author: thosakwe <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/galileo_mustache
version: 2.0.0
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  galileo_framework: #^2.0.0-alpha
    path: ../framework
  file: ^5.0.0
  mustache4dart: ^3.0.0-dev
  path: ^1.0.0
dev_dependencies:
  http: ^0.12.2
  test: ^1.15.7
