name: angel_sembast
description: package:sembast-powered CRUD services for the Angel framework.
homepage: https://github.com/angel-dart/sembast
version: 1.0.1
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.10.0 <2.12.0"
dependencies:
  angel_framework: #^2.0.0-alpha
    path: ../framework
  sembast: ^1.19.0-dev.2
dev_dependencies:
  angel_http_exception: #^1.0.0
    path: ../http_exception
  logging:
  pedantic: ^1.0.0
  test: ^1.15.7

