name: galileo_orm_postgres
version: 3.0.0
description: PostgreSQL support for galileo's ORM. Includes functionality for querying and transactions.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/orm

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_orm: ^3.0.0 
  logging: ^1.0.1 #Null safety
  pool: ^1.5.0 #Null safety
  galileo_postgres: ^3.0.0  #Null safety

dev_dependencies:
  galileo_orm_test: ^3.0.0   
  galileo_pretty_logging: ^3.0.0  #Null safety
  test: ^1.17.3  #Null safety
