name: galileo_orm_postgres
version: 2.0.0
description: PostgreSQL support for galileo's ORM. Includes functionality for querying and transactions.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/galileo-dart/orm
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  galileo_orm:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm
  logging: ^1.0.0
  pool: ^1.0.0
  postgres:
    git: 
      url: https://github.com/insinfo/postgresql-dart

dev_dependencies:
  galileo_orm_test:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm_test
  pretty_logging:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/pretty_logging
  test: ^1.15.7
