name: galileo_redis
version: 3.0.0
description: An Galileo service provider for Redis. Works well for caching volatile data.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/redis

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2 
  galileo_http_exception: ^2.0.2  #Null safety
  resp_client: ^1.2.0 #Null safety

dev_dependencies:
  test: ^1.17.3 #Null safety
