name: galileo_file_service
version: 3.0.0
description: galileo service that persists data to a file on disk.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/file_service

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2   
  file: ^6.1.0 # Null safety
  pool: ^1.5.0 # Null safety

dev_dependencies:
  test: ^1.17.3  # Null safety
