name: galileo_validate
description: Cross-platform request body validation library based on `matcher`.
version: 3.0.1
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2
  galileo_http_exception: ^2.0.2 #Null safety
  matcher: ^0.12.10 #Null safety
  
dev_dependencies:
  #galileo_test:  ^3.0.1 #Null safety
  build_runner: ^2.0.2 #Null safety
  build_web_compilers: ^3.0.0 #Null safety
  # logging: ^1.0.1 #Null safety
  galileo_mock_request: ^1.0.8 #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
