name: galileo_validate
description: Cross-platform request body validation library based on `matcher`.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git
#publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.0
  galileo_http_exception: ^2.0.1   
  matcher: ^0.12.0
  
dev_dependencies:
  #galileo_test:  
  build_runner: ^1.11.1
  build_web_compilers: ^2.12.2
#  logging: ^0.11.0
  galileo_mock_request:
  pedantic: ^1.0.0
  test: ^1.15.7