name: serialize
version: 1.0.0-alpha
description: package:galileo_serialize boilerplate generators.
dependencies:
  galileo_model: ^1.0.0
  galileo_serialize: ^1.0.0-alpha
dev_dependencies:
  galileo_serialize_generator: ^1.0.0-alpha
  build_runner: ^0.5.0
