name: serialize
version: 1.0.0-alpha
description: package:angel_serialize boilerplate generators.
dependencies:
  angel_model: ^1.0.0
  angel_serialize: ^1.0.0-alpha
dev_dependencies:
  angel_serialize_generator: ^1.0.0-alpha
  build_runner: ^0.5.0
