author: Isaque Neves <insinfo2008@gmail.com>
description: Shelf interop with Galileo. Use this to wrap existing server code.
homepage: https://github.com/galileo-dart/shelf
name: galileo_shelf
version: 3.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"
  
dependencies:
  galileo_framework: ^3.0.2   
  galileo_container: ^2.2.2 
  path: ^1.8.0 #Null safety
  shelf: ^1.1.1 #Null safety
  stream_channel: ^2.1.0  #Null safety
  galileo_mock_request: ^1.0.8 
  charcode: ^1.2.0 #Null safety

dev_dependencies: 
  galileo_test: ^3.0.1 
  pedantic: ^1.11.0  #Null safety
  galileo_pretty_logging: ^3.0.0  #Null safety
  shelf_static: ^1.0.0 #Null safety
  test: ^1.17.3 #Null safety
  http: ^0.13.3 #Null safety
  logging: ^1.0.1 #Null safety