name: angel_mongo
version: 2.0.3
description: MongoDB-enabled services for the Angel framework. Well-tested.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_mongo
environment:
  sdk: '>=2.10.0 <2.12.0'
dependencies:
  angel_framework: #^2.0.0-alpha
    path: ../framework
  json_god: ">=2.0.0-beta <3.0.0"
  merge_map: ^1.0.0
  mongo_dart: ^0.4.4
dev_dependencies:
  http: ^0.12.2
  pedantic: ^1.0.0
  test: ^1.15.7
