name: galileo_mongo
version: 3.0.0
description: MongoDB-enabled services for the Galileo framework. Well-tested.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/galileo_mongo

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  galileo_framework: ^3.0.2  
  galileo_json_god: ^3.0.1 
  galileo_merge_map: ^1.0.2 
  mongo_dart: ^0.7.0+1 #Null safety

dev_dependencies:
  http: ^0.13.3 #Null safety
  pedantic: ^1.11.0 #Null safety
  test: ^1.17.3 #Null safety
