name: galileo_admin
version: 3.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  galileo_auth: ^3.0.0 
  galileo_framework: ^3.0.2
  twig_dart: ^2.0.2
  galileo_seo: ^1.0.0
  galileo_static: ^3.0.1 
  galileo_validate: ^3.0.0 

dev_dependencies:
  galileo_file_service: ^1.0.0
  logging: ^1.0.1 #Null safety
