name: orm
version: 1.0.0-alpha
description: package:galileo_orm boilerplate generators.
dependencies:
  galileo_model: ^1.0.0
  galileo_orm: ^1.0.0-alpha
dev_dependencies:
  galileo_migration_runner: ^1.0.0-alpha
  galileo_orm_generator: ^1.0.0-alpha
  build_runner: ^0.5.0
