name: orm
version: 1.0.0-alpha
description: package:angel_orm boilerplate generators.
dependencies:
  angel_model: ^1.0.0
  angel_orm: ^1.0.0-alpha
dev_dependencies:
  angel_migration_runner: ^1.0.0-alpha
  angel_orm_generator: ^1.0.0-alpha
  build_runner: ^0.5.0
