name: galileo_sql_postgres
description: PostgreSQL bindings for package:galileo_sql, Galileo's SQL solution.
version: 1.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/galileo-dart/sql
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  galileo_sql:
    path: ../galileo_sql
  postgres: ^1.0.0
dev_dependencies:
  galileo_test: ^2.0.0-alpha
  http: ^0.12.0
  test: ^1.0.0
