name: galileo_migration
version: 3.0.0
description: Database migration runtime for galileo's ORM. Use this package to define schemas.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/galileo-dart/migration
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  galileo_orm:
    git: 
      url: https://github.com/insinfo/galileo.git
      ref: sdk-2.12.x
      path: packages/orm/galileo_orm