name: galileo_rethink
version: 3.0.0
description: RethinkDB-enabled services for the Galileo framework.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/rethink

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2
  galileo_json_god: ^3.0.1
  rethinkdb_dart: ^2.3.2+6

dev_dependencies:
  galileo_client: ^3.0.1     
  galileo_test: ^3.0.1   
  logging: ^1.0.1 #Null safety
  test: ^1.17.3 #Null safety
