name: angel_rethink
version: 1.1.0
description: RethinkDB-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.10.0 <2.12.0"
homepage: https://github.com/angel-dart/rethink
dependencies:
  angel_framework: #^1.1.0
    path: ../framework
  json_god: ^2.0.0-beta
  rethinkdb_dart: ^2.3.2+6
dev_dependencies:
  angel_client: #^1.1.0
    path: ../client
  angel_test: #^1.1.0
    path: ../test
  logging: ^0.11.3
  test: ^1.15.7