name: oauth
version: 0.4.0
author: Isaque Neves <insinfo2008@gmail.com>
description: An implementation of OAuth 1.0a per RFC 5849

homepage: https://github.com/insinfo/galileo/tree/master/packages/oauth_dart

environment:
    sdk: ">=2.10.0 <3.0.0"

dependencies:
  cipher: '>=0.7.0 <0.8.0'
  crypto: '^2.0.1'
  http: '>=0.10.0 <0.12.0'

dev_dependencies:
  shelf: '>=0.6.7+2'
  test: '>=0.10.0'
