name: galileo_seeder
description: Straightforward data seeder for Galileo services.
version: 3.0.0
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo/tree/master/packages/seeder

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  galileo_framework: ^3.0.2   
  faker: ^2.0.0-rc.2 #Null safety 

dev_dependencies:
  test: ^1.17.3 #Null safety 
