name: angel_seeder
description: Straightforward data seeder for Angel services.
version: 1.0.2
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.10.0 <2.12.0"
homepage: https://github.com/angel-dart/seeder
dependencies:
    angel_framework: #^1.0.0-dev
      path: ../framework
    faker: ^1.3.0
dev_dependencies:
    test: ^1.15.7
