name: lumberjack
version: 1.0.0-rc.1
author: Isaque Neves <insinfo2008@gmail.com>
description: Hierarchical logging for Dart. Supports multiple transports, zones, and more.
homepage: https://github.com/galileo-dart/lumberjack
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  logging: ^0.11.0
  intl: ^0.15.7
  io: ^0.3.2
  meta: ^1.0.0
  quiver_hashcode: ^2.0.0
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
