name: galileo_range_header
version: 3.0.0
description: Range header parser for Dart. Beyond parsing, a stream transformer is included.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/galileo.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  async: ^2.0.0 # 2.5.0 Null safety
  charcode: ^1.2.0
  quiver: ^3.0.1 # Null safety
  source_span: ^1.0.0 # 1.8.1 Null safety
  string_scanner: ^1.0.0 # 1.1.0 Null safety

dev_dependencies:
  galileo_framework:
  #galileo_static: 
  file:
  http_parser: 
  logging: 
  test: 