name: galileo_dart_language_server
version: 3.0.1
description: >-
  A shim on the analysis server following the language server protocol
homepage: https://github.com/insinfo/galileo/blob/master/packages/dart_language_server
author: Isaque Neves <insinfo2008@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analysis_server_lib: ^0.2.0 #Null safety
  args: ^2.1.0 #Null safety
  async: ^2.6.1 #Null safety
  json_rpc_2: ^3.0.1 #Null safety
  logging: ^1.0.1 #Null safety
  meta: ^1.3.0 #Null safety
  path: ^1.8.0 #Null safety
  pool: ^1.5.0 #Null safety
  stream_channel: ^2.1.0 #Null safety
  #stream_transform: ^0.0.20 #^2.0.0  #Null safety


dev_dependencies:
  build_runner: ^2.0.2 #Null safety
  galileo_message_builder: ^3.0.1
  test: ^1.17.3  #Null safety

executables:
  dart_language_server: dart_language_server
